// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anwjqitnsebjodlzgqxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFud2pxaXRuc2Viam9kbHpncXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTU0NDcsImV4cCI6MjA2OTczMTQ0N30.uyXaLIqA8xN3DryqsQR31VvmCzjfo3ROa19HwERlhFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});